config/routes.rb
Rails.application.routes.draw do
	get 'signup' => 'users#new'
	resources :users
	
  get 'welcome/index'
	resources :books
	
	get '/login' => 'sessions#new'
	
	post 'login' => 'sessions#create'
	
	delete 'logout' => 'sessions#destroy'
	
	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	
	has_secure_password
	
  def editor? 
    self.role == 'editor' 
  end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	
	helper_method :current_user 

	def current_user 
		@current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end
	
	def require_user 
	  redirect_to '/login' unless current_user 
	end
	
#	@username = User.find(session[:user_id]).first_name
	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :require_user, only: [:index, :show]
#  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
		@book[:user_id] = session[:user_id]

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	
	def create
    @user = User.find_by_email(params[:session][:email])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to '/books'
      else
				flash[:error] = "Incorrect user info.  Login again"
        redirect_to 'login'
      end 
  end
	
	def destroy 
    session[:user_id] = nil 
    redirect_to root_path 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	
	def create 
    @user = User.new(user_params) 
    if @user.save 
      session[:user_id] = @user.id 
      redirect_to '/books' 
    else 
      redirect_to '/signup' 
    end 
  end
	
# this makes current_user method avail in the views	
	helper_method :current_user 

# determine if a user is logged in or out, if so @current_user stores it	
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
	
# uses the current_user method to redirect logged out users to the login page
	def require_user 
    redirect_to '/login' unless current_user 
  end
	
	private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :book_description %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :book_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

 <h4><div class="welcome">Welcome 
	 <% if current_user %>
     <%= User.find(session[:user_id]).first_name %>
   <% end %>
 </div></h4>
<p></p>
<table>
  <thead>
    <tr>
      <th class="title">Title</th>
      <th class="author">Author</th>
      <th class="describe">Description</th>
      <th class="link">Download link</th>
      <th class="user_edit" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.description %></td>
        <td><%= book.url %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a New Book', new_book_path %>
<h4><%= link_to "Log out", logout_path, method: :delete %></h4>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>URL:</strong>
  <%= @book.url %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freeshelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
		
  </body>
</html>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">
			
			<h1>Sign up</h1>
        <%= form_for(@user) do |form| %>
				<div class="field">
					<%= form.label :first_name %>
          <%= form.text_field :first_name, :placeholder => "First name" %>
				</div>
			
			  <div class="field">
			    <%= form.label :last_name %>
          <%= form.text_field :last_name, :placeholder => "Last name" %>
			  </div>
			
			  <div class="field">
			    <%= form.label :email %>
          <%= form.email_field :email, :placeholder => "Email" %>
			  </div>
			
			  <div class="field">
			    <%= form.label :password %>
          <%= form.password_field :password, :placeholder => "Password" %>
			  </div>
			
			  <div class="actions">
          <%= form.submit "Create account", class: "btn btn-submit" %>
			  </div>
        <% end %>
			
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Freeshelf</h1>
<h1>An index of free, on-line programming books</h1>
<p></p>

<h2><%= link_to 'See the Book list', controller: 'books' %></h2>
<p></p>
<div class="nav"> 
	<h4><%= link_to "Log in", login_path %></h4>
	<h4><%= link_to "Sign up", new_user_path %></h4>
</div>